version: '3.8'

services:
  web:
    build: .
    container_name: library_web
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
